version: '2'
# login: user
# password: bitnami
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    # image: dirane/jenkins-docker-ansible-clair
    image: eazytraining/jenkins
    restart: always
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_home:/var/jenkins_home'
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local
