version: '2'
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    image: dirane/jenkins-docker-ansible-clair
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_data:
    driver: local
